'use strict';
const $=id=>document.getElementById(id);
const names={ANDREW_PANTON:'Andrew Panton',GAVIN_FREE:'Gavin Free',GEOFF_RAMSEY:'Geoff Ramsey',ERIC_BAUDOUR:'Eric Baudour',NICK_SCHWARTZ:'Nick Schwartz'};
let rows=[],current=null,token='',busy=false,clipEnd=0,dirty=false;
function message(text){$('status').textContent=text;}
for(const id of ['speaker','secondary']){const blank=new Option(id==='speaker'?'Choose after listening':'None','');$(id).add(blank);for(const [value,name]of Object.entries(names))$(id).add(new Option(name,value));}
function nav(){const term=$('search').value.toLowerCase();$('queue').replaceChildren();for(const row of rows.filter(r=>JSON.stringify(r.quote).toLowerCase().includes(term))){const b=document.createElement('button'),small=document.createElement('small'),text=document.createElement('span');small.textContent=`${row.quote.show} · Episode ${row.quote.episode}`;text.textContent=row.quote.quote;b.append(small,text);b.setAttribute('aria-current',String(current?.quote.id===row.quote.id));b.onclick=()=>{if(!busy)select(row);};$('queue').append(b);}}
function safeUrl(value){try{const u=new URL(value);return u.protocol==='https:'?u.href:null;}catch{return null;}}
function select(row){dirty=false;current=row;const q=row.quote,s=row.suggestion;$('audio').pause();$('video').replaceChildren();$('audio').hidden=true;$('review').hidden=false;$('empty').hidden=true;$('form').reset();$('episode').textContent=`${q.show} · Episode ${q.episode} · ${q.id}`;$('preview').textContent=`“${q.quote}”`;$('suggestion').textContent=s.speaker?`Suggested: ${names[s.speaker]} · ${s.score}% text agreement`:'Speaker: unknown · Confidence not available';$('basis').textContent=s.basis;$('existing').textContent=q.speaker?`Draft credit: ${names[q.speaker]||q.speaker} — not verified`:'';$('quote').value=q.quote;$('speaker').value=s.speaker||'';$('secondary').value=s.secondarySpeaker||'';$('show').value=q.show;$('number').value=q.episode;$('title').value=q.episodeTitle;$('videoid').value=q.youtubeVideoId||'';$('seconds').value=q.timestampSeconds??'';$('tags').value=(q.weatherTags||[]).join(', ');$('confirmed').checked=false;const url=safeUrl(q.source?.url||q.listenUrl);$('source').hidden=!url;if(url)$('source').href=url;$('playnote').textContent=row.audioUrl?'Podcast audio is available. Its segment timing may differ from YouTube.':'Enter or check the YouTube video and start time to preview. The source link can help locate the moment.';nav();}
function parseStamp(s){return(s||'0').split(':').reduce((n,p)=>n*60+Number(p),0);}
$('audio').addEventListener('timeupdate',()=>{if(clipEnd&&$('audio').currentTime>=clipEnd)$('audio').pause();});
$('play').onclick=()=>{if(!current)return;const vid=$('videoid').value.trim(),raw=$('seconds').value;const start=Number(raw);$('audio').pause();$('video').replaceChildren();if(/^[A-Za-z0-9_-]{11}$/.test(vid)&&raw!==''&&Number.isInteger(start)&&start>=0&&start<=86400){$('audio').hidden=true;const frame=document.createElement('iframe');frame.title='Quote playback preview';frame.allow='autoplay; encrypted-media';frame.src=`https://www.youtube-nocookie.com/embed/${vid}?start=${start}&end=${start+35}&autoplay=1`;frame.allowFullscreen=true;$('video').append(frame);$('playnote').textContent='YouTube preview. If embedding is unavailable, use the source link to listen.';}else if(current.audioUrl){const a=$('audio');a.hidden=false;a.src=current.audioUrl;const begin=Math.max(0,parseStamp(current.quote.source?.audioSegmentTimestamp)-5);clipEnd=begin+35;a.onloadedmetadata=()=>{a.currentTime=begin;a.play().catch(()=>message('Tap the audio play button to start.'));};a.onerror=()=>message('Audio could not load. Open the source link to listen.');a.load();$('playnote').textContent='35 seconds of podcast audio around the source segment. Verify YouTube timing separately.';}else message('Add the YouTube video ID and start time, or open the source link.');};
$('skip').onclick=()=>{if(rows.length&&!busy)select(rows[(rows.indexOf(current)+1)%rows.length]);};
$('search').oninput=nav;
async function load(){try{const r=await fetch('/api/queue');if(!r.ok)throw Error('Could not load queue');const data=await r.json();rows=data.rows;token=data.token;$('counts').textContent=`${rows.length} waiting · ${data.approved} approved`;if(rows.length)select(rows[0]);else{$('review').hidden=true;$('empty').hidden=false;$('empty').textContent='All caught up. Click Refresh queue to collect more candidates.';}nav();}catch(e){message(e.message);}}
$('reload').onclick=async()=>{
 if(busy)return;
 if(current&&dirty&&!confirm('Collect more quotes and leave this unsaved review?'))return;
 busy=true;$('reload').disabled=true;$('reload').textContent='Finding more…';message('Checking new and older episodes for more candidates…');
 try{const response=await fetch('/api/refresh',{method:'POST',headers:{'X-Review-Token':token}});const result=await response.json();if(!response.ok)throw Error(result.error);$('search').value='';await load();message(result.message);}
 catch(error){message(error.message);}
 finally{busy=false;$('reload').disabled=false;$('reload').textContent='Refresh queue';}
};
$('form').addEventListener('input',e=>{dirty=true;if(e.target.id!=='confirmed')$('confirmed').checked=false;});
$('form').onsubmit=async e=>{e.preventDefault();if(busy||!current)return;busy=true;$('approve').disabled=true;$('approve').textContent='Publishing…';const q=current;const edits={quote:$('quote').value.trim(),speaker:$('speaker').value,secondarySpeaker:$('secondary').value,show:$('show').value,episode:Number($('number').value),episodeTitle:$('title').value.trim(),youtubeVideoId:$('videoid').value.trim(),timestampSeconds:Number($('seconds').value),weatherTags:$('tags').value.split(',').map(x=>x.trim()).filter(Boolean),confirmed:$('confirmed').checked};try{const r=await fetch('/api/approve',{method:'POST',headers:{'Content-Type':'application/json','X-Review-Token':token},body:JSON.stringify({id:q.quote.id,fingerprint:q.fingerprint,edits})});const data=await r.json();if(!r.ok)throw Error(data.error);message(data.message);await load();}catch(e){message(e.message);}finally{busy=false;$('approve').disabled=false;$('approve').textContent='Approve & publish';}};
load();
